REM Segundo trabalho. 
REM testa a geração de código 

set path="C:\MinGW\bin";%path%

gcc -ansi -IC:\MinGW\include -o OK-CHK01.exe OK-CHK01.c 2> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-CHK02.exe OK-CHK02.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-CHK03.exe OK-CHK03.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-CHK04.exe OK-CHK04.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-CHK05.exe OK-CHK05.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-CHK06.exe OK-CHK06.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-CHK07.exe OK-CHK07.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER01.exe OK-GER01.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER02.exe OK-GER02.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER03.exe OK-GER03.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER04.exe OK-GER04.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER05.exe OK-GER05.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER06.exe OK-GER06.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER07.exe OK-GER07.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER08.exe OK-GER08.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER09.exe OK-GER09.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER10.exe OK-GER10.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER11.exe OK-GER11.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER12.exe OK-GER12.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER13.exe OK-GER13.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER14.exe OK-GER14.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER15.exe OK-GER15.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER16.exe OK-GER16.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER17.exe OK-GER17.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER18.exe OK-GER18.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER19.exe OK-GER19.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER20.exe OK-GER20.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER21.exe OK-GER21.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-GER22.exe OK-GER22.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-LEX02.exe OK-LEX02.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-LEX03.exe OK-LEX03.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-LEX04.exe OK-LEX04.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-LEX05.exe OK-LEX05.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-LEX06.exe OK-LEX06.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-LEX07.exe OK-LEX07.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-LEX08.exe OK-LEX08.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-LEX10.exe OK-LEX10.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM01.exe OK-SEM01.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM03.exe OK-SEM03.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM04.exe OK-SEM04.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM05.exe OK-SEM05.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM06.exe OK-SEM06.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM07.exe OK-SEM07.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM08.exe OK-SEM08.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM09.exe OK-SEM09.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM10.exe OK-SEM10.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM11.exe OK-SEM11.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM12.exe OK-SEM12.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM13.exe OK-SEM13.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM14.exe OK-SEM14.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM15.exe OK-SEM15.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM17.exe OK-SEM17.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM18.exe OK-SEM18.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM19.exe OK-SEM19.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SEM20.exe OK-SEM20.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN02.exe OK-SIN02.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN03.exe OK-SIN03.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN04.exe OK-SIN04.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN05.exe OK-SIN05.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN06.exe OK-SIN06.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN07.exe OK-SIN07.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN08.exe OK-SIN08.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN09.exe OK-SIN09.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN10.exe OK-SIN10.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN11.exe OK-SIN11.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN12.exe OK-SIN12.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN13.exe OK-SIN13.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN14.exe OK-SIN14.c 2>> ttt.txt
gcc -ansi -IC:\MinGW\include -o OK-SIN15.exe OK-SIN15.c 2>> ttt.txt